# Generated by Django 4.1.1 on 2022-09-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ['telefon']},
        ),
    ]
