# Generated by Django 4.1.1 on 2022-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0005_alter_basicinfo_options_remove_basicinfo_uryvek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vzdelani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('základní vzdělání', 'základní vzdělání'), ('Psychoterapeutický výcvik', 'Psychoterapeutický výcvik'), ('Doplňkové vzdělání', 'Doplňkové vzdělání'), ('Diagnostika', 'Diagnostika'), ('Pracovní zkušenosti', 'Pracovní zkušenosti'), ('Výzkum a teoretické práce', 'Výzkum a teoretické práce')], default='základní vzdělání', max_length=45)),
            ],
            options={
                'ordering': ['typ'],
            },
        ),
    ]
