# Generated by Django 4.1.1 on 2022-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0006_vzdelani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psycholog',
            fields=[
                ('id_psycholog', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
