# Generated by Django 4.1.1 on 2022-10-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0007_psycholog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='fk_psycholog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tata.psycholog'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='id_basicInfo',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
