# Generated by Django 4.1.1 on 2022-11-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0011_test_take'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='take',
            options={'ordering': ['test_id']},
        ),
        migrations.AlterField(
            model_name='client',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tata.user'),
        ),
    ]
