# Generated by Django 4.1.1 on 2022-11-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0012_alter_take_options_alter_client_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='psycholog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='take',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='take',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vzdelani',
            name='psycholog',
        ),
        migrations.DeleteModel(
            name='basicInfo',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Psycholog',
        ),
        migrations.DeleteModel(
            name='Take',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vzdelani',
        ),
    ]
