# Generated by Django 4.1.1 on 2022-11-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tata', '0013_remove_client_user_id_remove_psycholog_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psycholog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Vzdelani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('základní vzdělání', 'základní vzdělání'), ('Psychoterapeutický výcvik', 'Psychoterapeutický výcvik'), ('Doplňkové vzdělání', 'Doplňkové vzdělání'), ('Diagnostika', 'Diagnostika'), ('Pracovní zkušenosti', 'Pracovní zkušenosti'), ('Výzkum a teoretické práce', 'Výzkum a teoretické práce')], default='základní vzdělání', max_length=45)),
                ('psycholog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.psycholog')),
            ],
            options={
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.user')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.user')),
            ],
            options={
                'ordering': ['test_id'],
            },
        ),
        migrations.AddField(
            model_name='psycholog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tata.user'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tata.user')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='basicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provozovna', models.CharField(default='Hradecká 16, Opava', max_length=200)),
                ('telefon', models.CharField(default='+420 737 881 112', max_length=18)),
                ('email', models.EmailField(default='jbernard@hotmail.cz', max_length=254)),
                ('psycholog_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tata.psycholog')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
