# Generated by Django 4.1.1 on 2022-11-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Zde napište otázku', max_length=45)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.test')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='TakeAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.answers')),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.questions')),
                ('take_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.take')),
            ],
            options={
                'ordering': ['take_id'],
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.test'),
        ),
    ]
