# Generated by Django 4.1.1 on 2022-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0015_answers_questions_takeanswers_answers_question_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
