# Generated by Django 4.1.1 on 2022-11-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0016_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(default='Jan', max_length=200),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='surrname',
            field=models.CharField(default='Bernard', max_length=200),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='titul',
            field=models.CharField(default='Mgr.', max_length=18),
        ),
    ]
