# Generated by Django 4.1.1 on 2022-12-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0017_basicinfo_name_basicinfo_surrname_basicinfo_titul'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='Zde napište o čem tento test je'),
        ),
    ]
