# Generated by Django 4.1.1 on 2023-01-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0019_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata.typ'),
        ),
    ]
