# Generated by Django 4.1.1 on 2023-01-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0020_questions_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tata.typ'),
        ),
    ]
