# Generated by Django 4.1.1 on 2023-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0021_alter_questions_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default='Zde napište otázku', max_length=150),
        ),
    ]
