# Generated by Django 4.1.1 on 2023-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0024_alter_questions_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='cena_diagnostika',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='cena_poradenstvi_max',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='cena_poradenstvi_min',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='cena_supervize',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='cena_tymove_supervize',
            field=models.IntegerField(default=800),
        ),
    ]
