# Generated by Django 4.1.1 on 2022-09-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0003_alter_basicinfo_options_remove_basicinfo_telefon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='vzdelani',
            field=models.CharField(default='', max_length=200),
        ),
    ]
