# Generated by Django 4.1.1 on 2022-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0004_basicinfo_vzdelani'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='uryvek',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='vzdelani',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(default='jbernard@hotmail.cz', max_length=254),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='provozovna',
            field=models.CharField(default='Hradecká 16, Opava', max_length=200),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='telefon',
            field=models.CharField(default='+420 737 881 112', max_length=18),
        ),
    ]
