# Generated by Django 4.1.1 on 2022-11-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0008_remove_basicinfo_id_basicinfo_fk_psycholog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField( primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='fk_psycholog',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='psycholog_id',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='tata.psycholog'),
        ),
        migrations.AddField(
            model_name='psycholog',
            name='education',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='tata.vzdelani'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField( primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tata.user')),
            ],
            options={
                'ordering': ['id_client'],
            },
        ),
        migrations.AddField(
            model_name='psycholog',
            name='user_id',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='tata.user'),
        ),
    ]
