# Generated by Django 4.1.1 on 2022-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='kk', max_length=50),
        ),
    ]
